### ISSUE TITLE
fix.dateTime.day only returns second character

### ISSUE THREAD

**Issue by dave-sausages** [SlashDevin/NeoGPS#13]
When `Serial.println(fix.dateTime.day);` is used, it only prints the second character. For instance today is 27/09/2016 but only "7" gets printed.

However Serial.println(fix.dateTime.year); prints 16 as expected. 

This issue also occurs when passing the fix.dateTime.day value into a variable, not just with serial.print

**Comment by SlashDevin** [comment]
Well, I'll take the blame for naming the `day` member poorly.  :-(  The `fix.dateTime.day` member is actually the "day of the week".  I think you want the `fix.dateTime.date` member; that's the "day of the month".  Sorry!  I'm updating the comments and Data Model page to be more clear.

Also note that the `day` (of week) member is not normally calculated, because it's an expensive calculation.  When you really want the day-of-the-week, be sure to call `fix.dateTime.set_day()` sometime *after* `fix.dateTime` has been assigned (e.g., after `fix=gps.read()`).  You don't have to call `set_day` every time you use the `day` member, just when other `Time` members have been modified.
