### ISSUE TITLE
Advice wanted on using Neo6m GPS effciently

### ISSUE THREAD

**Issue by Bascy** [SlashDevin/NeoGPS#23]
We are investigating how to use our GPS Neo6m module to be as least time-consuming as possible in the following situation..

Our GPS is used for the following:
- Activate an indicator on a Nextion display when a valid fix is made (2 - 5 min interval would be acceptable)
- Log movement on a 1 to 30 seconds interval

This GPS functionality is part of a larger project of sensors (timed and interrupt driver) and activators, so every ms we spare on te GPS handling is welcome. We are wondering what would be the best way to achieve this, effectively ignoring all the data the gps is sending between "polling" intervals.

We though about using the interrupts mode of NeoGPS but wouldn't the interrupt handling still take time to process messages from the GPS when we are not really interested in the results?

Any advice is welcome!

**Comment by SlashDevin** [comment]
I would suggest using the interrupt mode, because it saves copying the recevied byte into the input buffer, polling for it in `loop`, and copying it back out of the input buffer with `gps_port.read()`.  That is most efficient.

To avoid handling character interrupts when you don't care about the GPS information, call `gps_port.end()`.      This disables the serial RX interrupt.  Then call `gps_port.begin` when you want GPS information again.

However, you have to consider that you will have to wait for the 2nd GPS update to guarantee that you have a complete fix.  You might be calling `begin` in the middle of a GPS update, perhaps receiving only one of several sentences.  Depending on what fields you need, what sentences you have enabled, what sentences the GPS device emits (and in what order), and the update interval (1s by default), you could end up waiting for **2 seconds** before the latest fix is really complete.

If you need low latency (i.e., quick access to the latest fix), you will have to continue parsing the GPS data in the background, even though you may not need some of the fixes.
