### ISSUE TITLE
GPS Data Errors - Dragino LoRa/GPS Arduino Mega

### ISSUE THREAD

**Issue by GurenMarkV** [SlashDevin/NeoGPS#65]
I am using Dragino LoRa/GPS Shield ontop of the Arduino Mega. I have the GPS_RX on Arduino TX(Pin18) and the GPS_TX on the Arduino RX(Pin19). I have tried all the sample codes and get weird results like year being 2080 and GPS data that is not accurate. When uploading the code I press the Reset switch on the Shield and have also tried not pressing it. The GPS light does not turn on. I have only had this working once before but it was on another computer and I don't have the setup that worked. Any help to get proper data would be greatly appreciated. I have tried commenting and uncommenting everything I could find that were in the Sample examples' notes. Using the NeoHWSerial and tested with the Default Serial setting. 

I am not using any modified code since I am trying to test the GPS currently for a future project. So here are all the pics of the tests I ran. 

This is the setup, I am testing without the Red LoRa module connected since that is how I got it to work before. But I do not remember any other connection I made. Maybe the Dragino Shield needs some extra connections to the Mega to get it working. 

![photo_2017-12-22_03-22-37](https://user-images.githubusercontent.com/9158618/34290814-69bcfb78-e6c7-11e7-9628-5124b10b6152.jpg)

![2017-12-22 9](https://user-images.githubusercontent.com/9158618/34290723-0406ca98-e6c7-11e7-9e3f-0e6123ff9739.png)

![2017-12-22 7](https://user-images.githubusercontent.com/9158618/34290730-0f9ba8d8-e6c7-11e7-9ca4-c9aee02b7ec0.png)

![2017-12-22 6](https://user-images.githubusercontent.com/9158618/34290739-174a5a2a-e6c7-11e7-9902-3cea7d3b1118.png)

![2017-12-22 5](https://user-images.githubusercontent.com/9158618/34290747-1dd7cf3a-e6c7-11e7-9710-a910f5d9613f.png)

![2017-12-22 3](https://user-images.githubusercontent.com/9158618/34290756-2618502a-e6c7-11e7-93fe-8051ac93fa32.png)

![2017-12-22 2](https://user-images.githubusercontent.com/9158618/34290764-2d19bf76-e6c7-11e7-9077-713236c7df88.png)

**Comment by SlashDevin** [comment]
It looks like you do not have good satellite reception.  The screen shot for NMEAdiagnostic show that the GPRMC sentence is reporting the date field as "050180", which NeoGPS interprets as January 1, 2080.  This is a "default" date from the GPS device, because it is not receiving anything from the satellites.

You probably need to move closer to a window or go outside.  It can take 10 minutes or more for the GPS device to get the first satellite lock, so be patient.

BTW, don't post screen shots.  Instead, select the text in the Serial Monitor window (mouse) and copy (ctrl-C) it.  Then paste it into your comment.  On github, put \```` before and after the text so it appears in a "code block", just like you do on the Arduino forum. 

````
It should look like this
````
